package MainGame.Interface;

import MainGame.AI.AIPlayer;
import MainGame.Interface.GamePanel;
import MainGame.Logic.Player;
import MainGame.Main;

import java.util.Random;

public class StartGUI extends javax.swing.JPanel {

    public  int boardSize;
    public  int size;

    public StartGUI() {
        initComponents();
    }

    //Set the size of the game board based on the size of the board
    private static int mapSize(int originalValue, int maximum, int minimum){
        return Math.round(600*(originalValue)/(maximum-minimum));
    }


    //Code generated by net beans
    private void initComponents() {

        jComboBoxDifficulty = new javax.swing.JComboBox<>();
        jButtonAI = new javax.swing.JButton();
        jButtonPlayer = new javax.swing.JButton();
        jLabelDifficulty = new javax.swing.JLabel();

        jComboBoxDifficulty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Easy", "Medium", "Hard", "Expert" }));

        jButtonAI.setText("Play as AI");
        jButtonAI.addActionListener(this::jButtonAIActionPerformed);

        jButtonPlayer.setText("Play as Player");
        jButtonPlayer.addActionListener(this::jButtonPlayerActionPerformed);

        jLabelDifficulty.setText("Select Difficulty");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButtonAI, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButtonPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabelDifficulty)
                                        .addComponent(jComboBoxDifficulty, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabelDifficulty)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxDifficulty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButtonPlayer)
                                        .addComponent(jButtonAI))
                                .addContainerGap(15, Short.MAX_VALUE))
        );
    }//

    private void getDifficulty(){
        //Based on the difficulty change attribute selectedDifficulty
        switch(jComboBoxDifficulty.getSelectedIndex()){
            case(0): {
                selectedDifficulty = 5;
                break;
            }
            case(1): {
                selectedDifficulty = 10;
                break;
            }
            case(2): {
                selectedDifficulty = 20;
                break;
            }
            case(3): {
                selectedDifficulty = 30;
                break;
            }
        }
        //using the selected difficulty create a random number
        size = new Random().nextInt(selectedDifficulty) + 20;
        boardSize = mapSize(size,50,20);
    }

    private void jButtonPlayerActionPerformed(java.awt.event.ActionEvent evt) {
        //If game started with player
        Random random = new Random();
        getDifficulty();
        //Put the player in a random place on the board
        Main.iPlayer = new Player(new int[]{random.nextInt(size), random.nextInt(size)});
        //Start the game
        Main.startGame(size, boardSize);
        //Close current panel
        Main.startFrame.dispose();
    }

    private void jButtonAIActionPerformed(java.awt.event.ActionEvent evt) {
        //If game started with AI
        Random random = new Random();
        getDifficulty();
        //Put the player in a random place on the board
        Main.iPlayer = new AIPlayer(new int[]{random.nextInt(size), random.nextInt(size)});
        //Start the game
        Main.startGame(size, boardSize);
        //Close current panels
        Main.startFrame.dispose();
    }



    private int selectedDifficulty;
    private javax.swing.JButton jButtonAI;
    private javax.swing.JButton jButtonPlayer;
    private javax.swing.JComboBox<String> jComboBoxDifficulty;
    private javax.swing.JLabel jLabelDifficulty;
    // End of variables declaration

}
